#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-slf4j
Version  : 1.5.6
Release  : 9
URL      : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
Source0  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.pom
Source5  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.jar
Source6  : https://repo.gradle.org/gradle/libs-releases/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.pom
Source7  : https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.jar
Source8  : https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.pom
Source9  : https://repo.maven.apache.org/maven2/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.jar
Source10  : https://repo.maven.apache.org/maven2/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.pom
Source11  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom
Source12  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
Source13  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
Source14  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12-sources.jar
Source15  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar
Source16  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom
Source17  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
Source18  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
Source19  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar
Source20  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.pom
Source21  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.5.2/slf4j-parent-1.5.2.pom
Source22  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom
Source23  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.16/slf4j-parent-1.7.16.pom
Source24  : https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
Source25  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom
Source26  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar
Source27  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.pom
Source28  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar
Source29  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.pom
Source30  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom
Source31  : https://repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar
Source32  : https://repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.pom
Source33  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.jar
Source34  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.pom
Source35  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
Source36  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
Source37  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar
Source38  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom
Source39  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar
Source40  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.pom
Source41  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar
Source42  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.pom
Source43  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar
Source44  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.pom
Source45  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
Source46  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom
Source47  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
Source48  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
Source49  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
Source50  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
Source51  : https://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
Source52  : https://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom
Source53  : https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
Source54  : https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom
Source55  : https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar
Source56  : https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.pom
Source57  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar
Source58  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.pom
Source59  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar
Source60  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.pom
Source61  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.3/slf4j-parent-1.5.3.pom
Source62  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom
Source63  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom
Source64  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.6.4/slf4j-parent-1.6.4.pom
Source65  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.10/slf4j-parent-1.7.10.pom
Source66  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom
Source67  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
Source68  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
Source69  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.jar
Source70  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.pom
Source71  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25-sources.jar
Source72  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
Source73  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.pom
Source74  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
Source75  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-slf4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-slf4j package.
Group: Data

%description data
data components for the mvn-slf4j package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.2
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.2/slf4j-parent-1.5.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.12
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.16
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.16/slf4j-parent-1.7.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3/slf4j-parent-1.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.1
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4/slf4j-parent-1.6.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.10
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.10/slf4j-parent-1.7.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.10/jcl-over-slf4j-1.7.10.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.jar
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.10/jul-to-slf4j-1.7.10.pom
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.jar
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.pom
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.jar
/usr/share/java/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.10/log4j-over-slf4j-1.7.10.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12-sources.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.2/slf4j-parent-1.5.2.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3/slf4j-parent-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4/slf4j-parent-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.10/slf4j-parent-1.7.10.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.16/slf4j-parent-1.7.16.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25-sources.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
