#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-slf4j
Version  : 1.5.6
Release  : 1
URL      : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
Source0  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
Source1  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom
Source2  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar
Source3  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.pom
Source4  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar
Source5  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.pom
Source6  : https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom
Source7  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.jar
Source8  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.pom
Source9  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
Source10  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
Source11  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar
Source12  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.pom
Source13  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
Source14  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom
Source15  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
Source16  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
Source17  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
Source18  : https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
Source19  : https://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
Source20  : https://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom
Source21  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar
Source22  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.pom
Source23  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar
Source24  : https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.pom
Source25  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.3/slf4j-parent-1.5.3.pom
Source26  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom
Source27  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.6.4/slf4j-parent-1.6.4.pom
Source28  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom
Source29  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
Source30  : https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
Source31  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25-sources.jar
Source32  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
Source33  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.pom
Source34  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
Source35  : https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-slf4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-slf4j package.
Group: Data

%description data
data components for the mvn-slf4j package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.3/slf4j-api-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.3/slf4j-parent-1.5.3.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.6.4/slf4j-parent-1.6.4.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25-sources.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.pom
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
/usr/share/java/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
